### ISSUE TITLE
 401 : Unauthorized CAS

### ISSUE THREAD

**Issue by AlAgcn** [cwaldbieser/jhub_cas_authenticator#20]
![401_1](https://user-images.githubusercontent.com/42209337/173857523-e9c0c79a-3be4-44e3-9a43-a10cd237f6be.png)

Hi im not able to start a server when I login. My CAS server shows, I complete with my user and password and succes, then I got stuck in that screen.
![login](https://user-images.githubusercontent.com/42209337/173855758-6f530f41-1647-4b71-9a0e-74599cd40057.png)

Thats logs

![config_1](https://user-images.githubusercontent.com/42209337/173856610-ab004786-48e5-4424-a569-74804ac267a0.png)

Thats my config.py

I already use CASAuthenticator (not Local) same problem.
I use normally with PAM authenticator, but I need massive user configuration

**Comment by cwaldbieser** [comment]
Hmm-- not exactly sure what is going on from your logs, but it looks like you browse to the JupyterHub service, it redirects you to CAS, you authenticate and are redirected back to JupyterHub with a service ticket in the URL, and then the JupyterHub rejects this as a 401.

Maybe set:

`c.Application.log_level = DEBUG` and check the logs again.  There are some debug logs in the code that should help you determine what the issue is.  FYI the code will return a 401 if any of these is the case:

- The service ticket is not valid.  E.g. the ST has expired or was forged.
- A required attribute is missing.  In your case, if CAS is not releasing "id".
- If you use a whitelist but the user is not in that list.  It doesn't look like you are doing that from your config.

Hope that helps!

**Comment by glciampaglia** [comment]
I don't know if this helpful given this issue from a few months ago, but I had the same problem (401 when redirecting to the service URL after successful login) and what fixed it for me was to comment out the line with `required_attribs =`.

**Comment by cwaldbieser** [comment]
Yes, if you don't require any attributes released from CAS for authorization, then you should comment out that setting.  I believe the default is an empty list (`[]`) if you want to have some kind of placeholder.
