### ISSUE TITLE
Whitelist doesn't limit access

### ISSUE THREAD

**Issue by liffiton** [cwaldbieser/jhub_cas_authenticator#8]
The authenticator whitelist doesn't seem to function for me.  I've tried setting both `c.Authenticator.whitelist` and `c.CASAuthenticator.whitelist` in `jupyterhub_config.py`, and in both cases, a CAS-authenticated user who is *not* in the whitelist is able to log in.

I deleted the user from within Jupyterhub's admin interface before each test, as the [docs](https://jupyterhub.readthedocs.io/en/latest/getting-started/authenticators-users-basics.html) suggest that a user in the database but not the config whitelist will still be able to log in.  Is it possible that there is some other hidden state leftover from the user's previous login that overrides the whitelist, or is CASAuthenticator itself overriding the whitelist?

**Comment by cwaldbieser** [comment]
It looks like this feature (along with blacklist) is only available in "supported authenticators"[1].  It looks like the CAS flow doesn't actually trigger the `get_authenticated_user()` function to be called, which would normally handle this.

I wouldn't be opposed to a PR to add this in.  Though you may be able to use the `cas_required_attribs` option to handle authorization rather than a whitelist/blacklist implemented at the service.

[1] https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py (see description around line 83)

**Comment by liffiton** [comment]
In my case, it was going to be simpler to use a whitelist than to ask IT to setup CAS attributes specific to my service, but yeah, I can go that way.

I was "inspired" by the example of using a whitelist in the README; do you know if it works with CASLocalAuthenticator?

Anyway, thanks for looking into it.
